services:
  postgres:
    image: postgres:16
    container_name: postgres-core
    environment:
      POSTGRES_DB: coredb
      POSTGRES_USER: coreuser
      POSTGRES_PASSWORD: corepass
    ports:
      - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U coreuser -d coredb"]
        interval: 5s
        timeout: 5s
        retries: 5

    volumes:
      - pgdata:/var/lib/postgresql/data

  core-service:
    build:
      context: ./backend/core-service/CoreService
    image: core-service:1.1
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__Postgres: Host=postgres;Port=5432;Database=coredb;Username=coreuser;Password=corepass
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "8080:8080"

volumes:
  pgdata:
